version: ""

formatter: markdown table

name:  terraform-aws-lambda-event-handler-ebs-burstbalance

content: |-
  # terraform-aws-lambda-event-handler-ebs-burstbalance

  GitHub: [StratusGrid/terraform-aws-lambda-event-handler-ebs-burstbalance](https://github.com/StratusGrid/terraform-aws-lambda-event-handler-ebs-burstbalance)

  This module will deploy a lambda function which will listen for ebs volume creation/deletion events and put/delete BurstBalance alarms for gp2 volumes. 
  
  ## Example:
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
